README.md
update ssh-agent instructions to work correctly across terminal instances
=> SSH-Agent updates

mac.sh
```
There are two important random numbers for the Yubikey you MUST keep safely.
See https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html
File "<string>", line 1
import random; print random.SystemRandom().randrange(10**7,10**8)
^
SyntaxError: invalid syntax
```
=> Support Python 3

expect.sh
Fixes https://github.com/DataDog/yubikey/issues/20
=> Fix expect for newer versions of YubiKey

README.md, expect.sh, git.sh, gpg.sh, realname-and-email.sh
=> Split gpg and git scripts

.gitignore, README.md, env.sh, expect.sh, gpg.sh, realname-and-email.sh, ssh.sh
=> Automate entering YubiKey PIN and admin PIN

README.md, env.sh, expect.sh, git.sh, gpg.sh, realname-and-email.sh, ssh.sh
Fixes #28, among other things, including minor documentation improvements.
=> Code cleanup and refactoring

README.md, reset.sh
Sometimes Corp IT get yubikeys back, then need to reset them, this script is here to facilitate that
=> CORPIT-1710 Add a script to reset a yubikey

README.md, env.sh, expect.sh, git.sh, gpg.sh, realname-and-email.sh, reset.sh, ssh.sh
=> Different policies depending on whether FIPS or not

reset.sh
- Improve output
- Let ykman manage the FIDO reset because you need to unplug then replug the key and touch it
before 
```bash
Usage: ykman fido reset [OPTIONS]
Try "ykman fido reset -h" for help.
Error: Reset failed. Reset must be triggered within 5 seconds after the YubiKey is inserted.
```
after 
```bash
WARNING! This will delete all FIDO credentials, including FIDO U2F credentials, and restore factory settings. Proceed? [y/N]: y
Remove and re-insert your YubiKey to perform the reset...
Touch your YubiKey...
```
=> Improve output and let ykman manage the FIDO reset

README.md, docs/optional.md
Add documentation to explain how to configure a computer to use an already configured Yubikey.
Fixes #51
=> Add documentation to configure a computer to use a configured Yubikey

README.md
Troubleshooting notes for an error that I encountered while setting up my yubikey. Credit goes to https://github.com/Yubico/yubikey-manager/issues/185
=> Updating README.md to include troubleshooting tip for No PyUSB error

expect.sh, gpg.sh
Specifically, we make the following changes:
```
PIN       ->  User PIN (OpenPGP)
PUK (PIV) -> Admin PIN (OpenPGP)
```
Need to make sure I didn't mess anything up.
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Do not conflate OpenPGP w/ PIV terminology

README.md, git.sh
@randomanderson please help to test?
@daisukixci please help review code?
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Option to sign git commits & tags for some not all repos

env.sh, gpg.sh
Here is a PR that specify which algorithms should be allowed or disabled.
=> Enforce cryptographic algorithms

README.md, env.sh, git.sh, gpg.sh, ssh.sh
Support several OS's to run it:
* Ubuntu
* Archlinux
* macOS
=> Prepare multi OS support

docs/troubleshooting.md
Add information about how to deal with errors resulting from using old MacOS bash version.
=> Add documentation about bash upgrade

expect.sh
With ykman 4, yubico changed a few command, this PR intend to update it.
source: https://www.yubico.com/blog/yubico-releases-yubikey-manager-cli-4-0/?utm_source=Twitter&utm_medium=unpd%3Asocial
=> Support ykman 4

env.sh, git.sh, realname-and-email.sh, ssh.sh
Harmonize the shebangs so we use the user env bash everywhere
=> Fix shebangs

README.md, env.sh, notification.sh
The notification script will shows a pop up to tell you to touch your yubikey each time you need sign a commit
=> Add notification script

env.sh, git.sh, gpg.sh, notification.sh, realname-and-email.sh, ssh.sh
- Remove bash > 4 requirements.txt
- Add color code for output
- Green = notification
- Yellow = Require interaction from user
- Red = Error
- Added Scdaemon configuration for macos to fix flaky usb detection after some upgrade. Thanks @platinummonkey who find the fix
- Improve notification script
=> Several minor improvements

gpg.sh
Feedback from user: a full path to the pub keys exported could be nice
=> Minor display improvement - Add full path to the pub keys exported

README.md, docs/optional.md, env.sh, expect.sh, git.sh, gpg.sh, notification.sh, notifications.sh
* Improve docs
* Turn on notifications by default when signing commits
* Fix a few permission-related issues
=> Improve docs and notifications

docs/troubleshooting.md, env.sh, git.sh, gpg.sh, import.sh, lib/git_conf.sh, lib/notifications.sh, lib/tree.sh
- Move the USER_BIN folder creation in the notfication lib
- Trigger notifications lib when importing git config
- Add m1 error troubleshooting
- Fix dir tree creation during import
- Fix #96 
- Only add yubico repo if missing on Ubuntu
=> Multiples fixes

README.md, ssh.sh
* Improve README explanation of ssh on yubikey
* fix a small bug in ssh.sh
* now with more signing
closes #99
=> Update README with better explanation of the ssh.sh script

env.sh
Fix the notify variable assignment
Fix #105
=> Fix the notify variable assignment

expect.sh
=> Fix #107 Update ykman expected syntax

expects/expect-ubuntu.sh
Ykman once again changed output. This fixes it, credits to @EdTheBearded who submitted the patch
=> Fix #112 Update Ubuntu expect syntax
